"""Weekly waste report generation (1B-6).

Produces formatted waste reports in plain text and Slack Block Kit
format. Designed to be called from the CLI (`agentproof waste-report`)
or scheduled as a periodic task.
"""

from __future__ import annotations

from agentproof.waste.types import WasteItem, WasteReport, WasteSeverity

# Slack emoji mapping, mirrors the pattern in alerts/notify.py
_SEVERITY_EMOJI: dict[WasteSeverity, str] = {
    WasteSeverity.INFO: ":information_source:",
    WasteSeverity.WARNING: ":warning:",
    WasteSeverity.CRITICAL: ":rotating_light:",
}

_CATEGORY_LABELS: dict[str, str] = {
    "model_overkill": "Model Overkill",
    "redundant_calls": "Redundant Calls",
    "context_bloat": "Context Bloat",
    "cache_misses": "Cache Misses",
    "agent_loops": "Agent Loops",
}


def format_plain_text(report: WasteReport, *, top_n: int = 5) -> str:
    """Render a waste report as plain text for CLI output or email."""
    if not report.items:
        return (
            "AgentProof Weekly Waste Report\n"
            "==============================\n\n"
            "No waste detected. All systems operating efficiently.\n"
        )

    lines: list[str] = [
        "AgentProof Weekly Waste Report",
        "==============================",
        "",
        f"Waste Score: {report.waste_score:.0%}",
        f"Total Potential Savings: ${report.total_savings:,.2f}",
        f"Total Spend: ${report.total_spend:,.2f}",
        "",
        f"Top {min(top_n, len(report.items))} Waste Items",
        "-" * 40,
    ]

    for i, item in enumerate(report.items[:top_n], 1):
        label = _CATEGORY_LABELS.get(item.category.value, item.category.value)
        lines.extend([
            f"\n{i}. [{item.severity.value.upper()}] {label}",
            f"   {item.description}",
            f"   Savings: ${item.savings:,.2f} | Calls: {item.call_count:,}",
            f"   Current: ${item.current_cost:,.2f} -> Projected: ${item.projected_cost:,.2f}",
        ])

    # Category summary
    savings_by_category: dict[str, float] = {}
    for item in report.items:
        cat = item.category.value
        savings_by_category[cat] = savings_by_category.get(cat, 0) + item.savings

    lines.extend([
        "",
        "Savings by Category",
        "-" * 40,
    ])
    for cat, savings in sorted(savings_by_category.items(), key=lambda x: x[1], reverse=True):
        label = _CATEGORY_LABELS.get(cat, cat)
        lines.append(f"  {label}: ${savings:,.2f}")

    lines.extend([
        "",
        "---",
        "Generated by AgentProof | View details in the dashboard",
    ])

    return "\n".join(lines)


def format_slack_blocks(report: WasteReport, *, top_n: int = 5) -> list[dict]:
    """Render a waste report as Slack Block Kit blocks.

    Follows the same pattern as alerts/notify.py format_slack_blocks.
    """
    if not report.items:
        return [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "AgentProof Weekly Waste Report"},
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": ":white_check_mark: No waste detected. All systems operating efficiently.",
                },
            },
        ]

    score_emoji = ":red_circle:" if report.waste_score > 0.5 else (
        ":large_yellow_circle:" if report.waste_score > 0.2 else ":large_green_circle:"
    )

    blocks: list[dict] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "AgentProof Weekly Waste Report"},
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"{score_emoji} *Waste Score:* {report.waste_score:.0%}\n"
                    f"*Total Potential Savings:* ${report.total_savings:,.2f}\n"
                    f"*Total Spend:* ${report.total_spend:,.2f}"
                ),
            },
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Top {min(top_n, len(report.items))} Waste Items*",
            },
        },
    ]

    for item in report.items[:top_n]:
        emoji = _SEVERITY_EMOJI.get(item.severity, ":grey_question:")
        label = _CATEGORY_LABELS.get(item.category.value, item.category.value)
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"{emoji} *{label}*\n"
                    f"{item.description}\n"
                    f"Savings: *${item.savings:,.2f}* | "
                    f"Calls: {item.call_count:,}"
                ),
            },
        })

    # Category summary
    savings_by_category: dict[str, float] = {}
    for item in report.items:
        cat = item.category.value
        savings_by_category[cat] = savings_by_category.get(cat, 0) + item.savings

    summary_lines = []
    for cat, savings in sorted(savings_by_category.items(), key=lambda x: x[1], reverse=True):
        label = _CATEGORY_LABELS.get(cat, cat)
        summary_lines.append(f"  {label}: *${savings:,.2f}*")

    blocks.extend([
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Savings by Category*\n" + "\n".join(summary_lines),
            },
        },
    ])

    return blocks
