"""Deterministic Merkle tree for anchoring trace evaluations on-chain.

Uses SHA-256 with sorted-pair hashing so that the same set of leaves
always produces the same root regardless of insertion order within
each pair. Pads to the next power of two with empty-leaf hashes.

The tree retains all layers so that inclusion proofs can be generated
after construction.
"""

from __future__ import annotations

import hashlib


# Sentinel hash used to pad the leaf layer to a power of two
EMPTY_LEAF = hashlib.sha256(b"").hexdigest()


class MerkleTree:
    """Binary Merkle tree with sorted-pair hashing.

    Accepts leaf data as bytes or strings, hashes each to produce the
    leaf layer, then builds upward. The sorted-pair rule ensures
    hash(min(a,b) + max(a,b)) so left/right ordering within a pair
    doesn't affect the result.
    """

    def __init__(self, leaves: list[bytes | str]) -> None:
        if not leaves:
            self._layers: list[list[str]] = [[EMPTY_LEAF]]
            return

        leaf_hashes = [self.leaf_hash(leaf) for leaf in leaves]

        # Pad to next power of two
        next_pow2 = 1
        while next_pow2 < len(leaf_hashes):
            next_pow2 <<= 1
        while len(leaf_hashes) < next_pow2:
            leaf_hashes.append(EMPTY_LEAF)

        self._layers = [leaf_hashes]
        current = leaf_hashes

        while len(current) > 1:
            next_layer: list[str] = []
            for i in range(0, len(current), 2):
                left, right = current[i], current[i + 1]
                next_layer.append(_hash_pair(left, right))
            self._layers.append(next_layer)
            current = next_layer

    @property
    def root(self) -> str:
        """Hex string of the Merkle root."""
        return self._layers[-1][0]

    @property
    def layers(self) -> list[list[str]]:
        """All tree layers, from leaves (index 0) to root (index -1)."""
        return self._layers

    def get_proof(self, leaf_index: int) -> list[tuple[str, str]]:
        """Generate a Merkle inclusion proof for the leaf at the given index.

        Returns a list of (sibling_hash, position) tuples where position
        is 'left' or 'right', indicating where the sibling sits relative
        to the node being proved.
        """
        if leaf_index < 0 or leaf_index >= len(self._layers[0]):
            raise IndexError(
                f"leaf_index {leaf_index} out of range for tree with "
                f"{len(self._layers[0])} leaves"
            )

        proof: list[tuple[str, str]] = []
        idx = leaf_index

        for layer in self._layers[:-1]:
            if idx % 2 == 0:
                sibling_idx = idx + 1
                position = "right"
            else:
                sibling_idx = idx - 1
                position = "left"

            if sibling_idx < len(layer):
                proof.append((layer[sibling_idx], position))
            idx //= 2

        return proof

    @staticmethod
    def verify_proof(leaf_hash: str, proof: list[tuple[str, str]], root: str) -> bool:
        """Verify that a leaf is included in the tree with the given root.

        Uses the same sorted-pair hashing as construction so that proofs
        generated by get_proof() round-trip correctly.
        """
        current = leaf_hash

        for sibling, position in proof:
            if position == "left":
                left, right = sibling, current
            else:
                left, right = current, sibling

            current = _hash_pair(left, right)

        return current == root

    @staticmethod
    def leaf_hash(data: bytes | str) -> str:
        """Hash a single leaf value to its Merkle leaf representation."""
        if isinstance(data, str):
            data = data.encode("utf-8")
        return hashlib.sha256(data).hexdigest()


def _hash_pair(a: str, b: str) -> str:
    """Sorted-pair hash: always hash min first for order independence."""
    if a > b:
        a, b = b, a
    return hashlib.sha256(bytes.fromhex(a) + bytes.fromhex(b)).hexdigest()
